services:
  lorawan-multiplexer-converter:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    command: -c /etc/lorawan-multiplexer-converter/config.toml
    volumes:
      - ./config.toml:/etc/lorawan-multiplexer-converter/config.toml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"