name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Install protoc
        run: |
          curl -fsSL https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip -o protoc.zip
          sudo unzip protoc.zip -d /usr/local
          rm protoc.zip
      -
        name: Cargo cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Run tests
        run: cargo test
